FROM osrf/ros:noetic-desktop-full

# Set non-interactive mode to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary system dependencies and ROS tools (excluding pre-built PCL ROS packages)
RUN apt-get update && apt-get install -y \
    gedit \
    nano \
    git \
    build-essential \
    cmake \
    python3-pip \
    python3-rosdep \
    python3-catkin-tools \
    locales \
    libyaml-cpp-dev \
    ros-noetic-cv-bridge \
    ros-noetic-image-transport \
    ros-noetic-tf2-geometry-msgs \
    ros-noetic-message-filters \
    ros-noetic-geometry-msgs \
    ros-noetic-sensor-msgs \
    ros-noetic-eigen-conversions \
    ros-noetic-catkin \
    && rm -rf /var/lib/apt/lists/*

# Create the workspace and build kalibr in it
ENV WORKSPACE=/home/catkin_ws
ENV THIRD_PARTY=/home/third_party

RUN mkdir -p $THIRD_PARTY && \
    mkdir -p $WORKSPACE/src && \
	cd $WORKSPACE 

RUN cd $THIRD_PARTY && \
    git clone -b pcl-1.14.0 https://github.com/PointCloudLibrary/pcl pcl-1.14.0 && \
    cd pcl-1.14.0 && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    echo "$(cat kdtree/CMakeFiles/pcl_kdtree.dir/link.txt) -llz4" > kdtree/CMakeFiles/pcl_kdtree.dir/link.txt && \
    make install -j4 && \
    cd ../.. && \
    rm -rf pcl-1.14.0

RUN cd $THIRD_PARTY && \
    git clone -b 3.3.7 https://gitlab.com/libeigen/eigen.git && \
    cd eigen && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make install -j4 && \
    cd ../.. && \
    rm -rf eigen

RUN cd $THIRD_PARTY && \
    git clone -b 4.2.0 https://github.com/opencv/opencv.git && \
    cd opencv && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DINSTALL_C_EXAMPLES=OFF \
             -DINSTALL_PYTHON_EXAMPLES=OFF && \
    make install -j4 && \
    cd ../.. && \
    rm -rf opencv


RUN cd $THIRD_PARTY && \
    git clone https://github.com/strasdat/Sophus.git && \
    cd Sophus && \
    git checkout a621ff2e56c56c839a6c40418d42c3c254424b5c && \
    sed -i 's/unit_complex_.real() = 1.;/unit_complex_ = std::complex<double>(1,0);/' sophus/so2.cpp && \
    sed -i 's/unit_complex_.imag() = 0.;//g' sophus/so2.cpp && \
    mkdir build && \
    cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-Wno-error=int-in-bool-context" && \
    make install -j4 && \
    cd ../.. 


# Clone Vikit
RUN cd $WORKSPACE/src && \
    git clone https://github.com/xuankuzcr/rpg_vikit.git 

# Clone and build livox_ros_driver
RUN cd $WORKSPACE/src && \
    git clone https://github.com/Livox-SDK/livox_ros_driver.git

RUN bash -c "echo 'source /opt/ros/noetic/setup.bash' >> ~/.bashrc"

WORKDIR /home


